name: Lighthouse CI
on: 
  push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:3000/
            http://localhost:3000/signin
            http://localhost:3000/login
            http://localhost:3000/user
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          runs: 2
          env:
          LHCI_GITHUB_APP_TOKEN: $67fDLG6CPUom1:35318614:bYND5RiGauE